### ISSUE TITLE
dist_weighted_hamming

### ISSUE THREAD

**Issue by gongx030** [ikwak2/DCLEAR#1]
@ikwak2 Could you please use `dist_weighted_hamming` for your function?  Please see `dist_weighted_hamming.r`.  I think the function name is more intuitive for the users.  Thanks.

**Comment by gongx030** [comment]
BTW, when you got chance, could you please also implement a version to compute the weighted hamming distance between two matrices, like:

`setMethod('dist_weighted_hamming', signature(x = 'phyDat', y = 'phyDat'), function(x, y, ...)`

**Comment by ikwak2** [comment]
Ok, I will work on it, thanks :)
