### ISSUE TITLE
Question about reproducing subchallenge 2 results

### ISSUE THREAD

**Issue by uWnosliW** [ikwak2/DCLEAR#4]
Hi, 

I was trying to reproduce the results of subchallenge 2 by rerunning the code in the ["Preparation for subchallenge 2 submission"](https://ikwak2.github.io/tmphtml/PrepC2) notebook. Everything works well until the function `compute_replacement_matrix` gets called at the end. An error is thrown since this function doesn't seem to be defined anywhere in the codebase. **Is this function implemented somewhere?**

Instead, I tried to fix this by not running `compute_replacement_matrix` at all and instead running the `dist_replacement` function **without** first computing the `kmer_summary` object. Specifically, I tried replacing the following three lines 
```
S <- compute_replacement_matrix(x = x, n_batch = n_batch, k = k, mc.cores = 8)
d <- dist_replacement(x, S)
tree <- d %>% fastme.bal()
```
with 
```
tree <- x %>% 
  dist_replacement(reps = 20L, k = 2L)  %>% 
  NJ()
```
Are these equivalent? 

Thanks in advance! 
Wilson

**Comment by gongx030** [comment]
@uWnosliW Thanks for your interest in DCLEAR. Yes you are correct that we have updated the functions and latest usage can be found in this colab notebook: https://colab.research.google.com/gist/gongx030/653a76bffc4ee6ff41499e0026b6d39a/krd.ipynb.  

Please let us know if you have any questions.
